### ISSUE TITLE
Idea: Provide a backchannel from raspi to the android app

### ISSUE THREAD

**Issue by Ho-Ro** [martinohanlon/BlueDot#101]
I could think about blinking the blue dot on the android phone triggered by the python program on raspi, e.g. as a visual feedback. 
Another good thing would be an optional status line on the android phone showing a feedback text sent from python.

**Comment by martinohanlon** [comment]
Its a great idea, but this would be a different solution (and one I am working on btw).

The purpose behind Blue Dot is that it is SUPER simple, super api, simple technology, always works and simple 1 way comms make that possible.

Blue Dot should be thing you start a project with, not the thing you always use.
