### ISSUE TITLE
ObjectManager doesn't exist error

### ISSUE THREAD

**Issue by TheHardestBunnyAlive** [martinohanlon/BlueDot#105]
I've been trying to get BlueDot to work all day and have still come up empty. My mydot.py script consists of the example code that is given in the tutorial.
from bluedot import BlueDot
bd = BlueDot()
bd.wait_for_press()
print("You pressed the blue dot!")
When I attempt to run this script however, I get this error in console
https://gyazo.com/fd9b8dfb9521543f7eb5c9339eeb17d2
What's going on here and how do I fix it?

**Comment by ukBaz** [comment]
Hello.

Firstly, it would be more helpful if you could paste the text from the console in the github issue rather than a screenshot (especially one that is a link to another website).

The next thing I noticed was that it is complaining about line 16 of the `mydot.py` script. Above you only have four lines. What is the rest of your `mydot.py` script?

You don't say what hardware you are trying to run this on. It would also be helpful to know the operating system and version.

In the console could you let me know the output from the following commands.
To find the version of BlueZ:
`bluetoothctl -v`

To find what Bluetooth controllers you have on your system:
`btmgmt info`

Thanks,
Barry

**Comment by ukBaz** [comment]
I suspect the issue might be around the version of Raspbian and/or the hardware you are using.
I have no easy way of testing as I don't have access to that hardware. I know the Raspberry Pi Model A did not support Bluetooth on the board itself so how are you adding the Bluetooth hardware? Is it a with a Bluetooth USB dongle?
Also the development of Bluetooth has been quite rapid on Linux with many changes to the kernel and userspace daemon. I suspect there is not even a Bluetooth service running on your machine currently. You could test this with the following command:
`service bluetooth status`

I suspect if you are going to be successful with a Model A (with an added Bluetooth USB dongle) then upgrading to the latest Raspbian (Stretch) is going to be your easiest option in my opinion.

**Comment by TheHardestBunnyAlive** [comment]
Yeah so I just ran the command and it does say the bluetooth is running. I'm using a rocketfish Bluetooth dongle. Perhaps I installed something, somewhere incorrectly? I've gone through this [tutorial (http://bluedot.readthedocs.io/en/latest/gettingstarted.html). 

Is there an easy way to upgrade the operating system and if so perhaps that would be the best idea?

**Comment by ukBaz** [comment]
What was the version reported when you ran the command to test for the Bluetooth service?

I've done some research and the version of BlueZ that was default in Wheezy is BlueZ 4.99. If that is the case then the error message you saw makes sense. At 4.99 the adapter information was located at [org.bluez.Adapter](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt?h=4.99#n14) as opposed to the newer versions which have the adapter information located at [org.bluez.Adapter1](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/adapter-api.txt?h=5.43)

Unless you have something else on your system you don't want to lose I would suggest you upgrade your system with a new image. One of the advantages of the Raspberry Pi is, that if you have another SD card, you could just swap the cards over to test with a new version of the operating system.
Instructions on how to download and install a newer operating system can be found at: 
https://www.raspberrypi.org/documentation/installation/installing-images/

**Comment by TheHardestBunnyAlive** [comment]
When I ran `service bluetooth status`, all it says is [ ok ] bluetooth is running. It doesn't give any version numbers. Currently I'm downloaded the latest Raspbian OS on another SD card. I'll give it a go and see if that fixes it.

**Comment by TheHardestBunnyAlive** [comment]
After reinstalling Raspbian OS on a new SD card I finally got the script to run and work properly.

One last thing that doesn't relate to the issue is how to drive motors using bluedot.
Currently I have a script which drives the motors depending on which key you press on your keyboard.
`import RPi.GPIO as gpio
import time

try:
	gpio.setmode(gpio.BCM)
        gpio.setup(17, gpio.OUT)
	gpio.setup(22, gpio.OUT)

	gpio.setup(10, gpio.OUT)
	gpio.setup(9, gpio.OUT)


	gpio.output(17, True)
	gpio.output(22, True)
	
	gpio.output(10, True)
	gpio.output(9, True)

	while True:
   		 gpio.output(17, True)
   		 gpio.output(22, False)

		 gpio.output(10, False)
		 gpio.output(9, True)


   		 time.sleep(2)


   		 gpio.output(17, False)
   		 gpio.output(22, True)
		
		 gpio.output(10, True)
		 gpio.output(9, False)
   		 time.sleep(2)
finally:
		 gpio.cleanup()
`
How would I get the BlueDot to do the same but without the keys?

Thanks,
Bunny

**Comment by ukBaz** [comment]
Great! Glad you got it working.  And I appreciate you for letting us know that you got it work. Enjoy!

**Comment by martinohanlon** [comment]
Sorry, Im late to the party... I missed this notification.

Yes as you have worked out, Blue Dot needs Raspbian Jessie +.

Bluetooth support in Wheezy was sketchy at best.

**Comment by martinohanlon** [comment]
Thanks @ukBaz for the excellent support :)
