### ISSUE TITLE
my screen is just white when I open the app.

### ISSUE THREAD

**Issue by Zxtreme03** [martinohanlon/BlueDot#106]
The screen does not show any options to pair to a device.

**Comment by ukBaz** [comment]
Sorry but I think you are going to have to give me a little more context than that if I am to help.

Before opening the app, did you follow the pairing instructions?
http://bluedot.readthedocs.io/en/latest/pairpiandroid.html

**Comment by martinohanlon** [comment]
Do you mean the Blue Dot Android app? 

If so as @ukBaz says you need to pair your Raspberry Pi to your Android phone.

**Comment by martinohanlon** [comment]
@Zxtreme03 as you have opened #107 - have got past this problem? Can I close this issue?

**Comment by Zxtreme03** [comment]
Yes you can
