### ISSUE TITLE
Raspberry Pi to Raspberry Pi not connecting

### ISSUE THREAD

**Issue by Zxtreme03** [martinohanlon/BlueDot#107]
I am getting Error:  {Erno 111}   Connection Refused

**Comment by martinohanlon** [comment]
Can you give me a little more information?

What are you doing? Are you using 2 Pi's? 1 Pi + Android phone?
What does your code look like?

Generally `connection refused` means that you are trying to connect and there is nothing to connect to.
 - is your blue dot program running on your Pi?
 - have you paired your Pi?
 - are you connecting to your Pi and not something else?

**Comment by Zxtreme03** [comment]
I am connecting 2 raspberry Pis together. And the program is running.

**Comment by martinohanlon** [comment]
Ok, so you are running `bluedotapp` on 1 raspberry pi, and your "server" python program on the other?

Can you share your code? Screenshots of both Pi's would be useful.

**Comment by martinohanlon** [comment]
No response, closing. Feel free to reopen if you still have issues.
