### ISSUE TITLE
Starting November 1 Android app updates need to target API level >= 26 (Oreo)

### ISSUE THREAD

**Issue by tvoverbeek** [martinohanlon/BlueDot#114]
Currently the target API level is 25 (at least in github).
Suggest to rebuild the App for API level 26 or maybe even for 28 (Android Pie)

**Comment by martinohanlon** [comment]
Thanks for the issue, I was aware. I will rebuild the app before the deadline.

**Comment by tvoverbeek** [comment]
@martinohanlon My guess was that you were aware, but just wanted to make sure.

**Comment by martinohanlon** [comment]
Updated to use sdk level 27. The new version is currently in Beta release. I'll give it a week then release to production.

**Comment by martinohanlon** [comment]
Rolled the latest version into production a couple of days ago.  No reported issue. Thanks
