### ISSUE TITLE
'MockBlueDot' object has no attribute '_launch_mock_app2'

### ISSUE THREAD

**Issue by esarantanen** [martinohanlon/BlueDot#120]
Thanks, updated to v1.3, however:

File "usr/local/lib/python3.5/dist-packages/bluedot/mock.py", line 262, in launch_mock_app
self._mock_app_thread = WrapThread(target=self._launch_mock_app2)
AttributeError: 'MockBlueDot' object has no attribute '_launch_mock_app2'

**Comment by martinohanlon** [comment]
Thanks, it was a pretty big release, there was bound to be something. I'll do a bug fix in the next or so.

**Comment by martinohanlon** [comment]
Fixed in v1.3.1
