### ISSUE TITLE
Using Bluedot with ESP32? 

### ISSUE THREAD

**Issue by moelski** [martinohanlon/BlueDot#125]
Hello, 
using this for Raspberry Pi is fine. But there are other devices for controlling stuff like the ESP32 - which also can handle Bluetooth (even BLE). 
So has anyone tried to get BlueDot working with an ESP32 instead of Raspberry Pi? 
And if not ... What should I do on the ESP32 site to get this working? 

regards
    Dominik

**Comment by martinohanlon** [comment]
A ESP32 library would have to be written which could communicate with a BlueDot app.

The BlueDot protocol can be found in the documentation https://bluedot.readthedocs.io/en/latest/protocol.html

This is not something I would progress as it doesn't fulfill the priorities of the project, but it 'seems' possible.
