### ISSUE TITLE
no services which can be used with Raspberry Pi

### ISSUE THREAD

**Issue by mtyeager** [martinohanlon/BlueDot#146]
I have gone through the Bluetooth pairing and connection info. The Raspberry Pi pairs to the android phone, but it shows the message "Paired successfully, but this device has no services which can be used with Raspberry Pi." When I launch BlueDot I see the Raspberry Pi, and can click on it, but get the message "unable to connect". I don't see any additional guidance in the readme. Any thoughs?

**Comment by mtyeager** [comment]
Nevermind. When I run the python script on the pi, it does connect. Not a problem. Thanks.

**Comment by martinohanlon** [comment]
Yes. The error is basically saying 'there are no services running on the Pi' (yet) . Your python program is this service your phone will connect too.

**Comment by mtyeager** [comment]
Hi Martin,

I have been trying to run the bluedot Bluetooth server in a docker container on RPi 4 (slim-buster).

It keeps failing on import dbus, giving me a modulenotfound error, even though I have RUN apt-get install python3-dbus in the dockerfile.

The Bluetooth server runs fine directly on the RPi hardware, but gives me this error when I try to run it in a docker container.

Any thoughts?

Thanks,

Michael

**Comment by martinohanlon** [comment]
@mtyeager Not a clue. Sorry.

My experience of using docker (on a pi or otherwise) is zero.

**Comment by ukBaz** [comment]
No idea on docker either but I was curious so I did a search which turned up this:
https://georgik.rocks/how-to-start-d-bus-in-docker-container/

Does that help you @mtyeager ?

**Comment by mtyeager** [comment]
Thanks Barry,

My issue is failure on the import dbus…

Do you think that would fail because dbus isn’t running? I thought it would be because it wasn’t installed, or it was installed, but it couldn’t find it…

Thanks so much for your help.

Michael

**Comment by virtadpt** [comment]
If `import dbus` is failing in your code, you don't have the `dbus` Python module in your container.

**Comment by mtyeager** [comment]
Yes, thanks Martin,

Sorry I bothered you with this. It was because I built the image on top of “Slim-buster”.

Which is slim. Not like standard Raspbian…

Once I installed a whole lot of things, it started working properly.

All the best. Stay safe.

Thanks,

Michael
