### ISSUE TITLE
raspberry bluetooth connecte yes then no

### ISSUE THREAD

**Issue by ronhud** [martinohanlon/BlueDot#147]
I have Bluedot on my android phone and it is paired with my raspberry pi.   With the raspberry terminal window open I use Bluedot on my phone and try to connect.  In the terminal window i get the device id and connected yes followed by the id and connected no.  Any suggestion as to a likely reason and fix?

**Comment by ukBaz** [comment]
Is this the same as #146 ?

Do you have the python script running on the raspberry pi?
Can you share that script? Or use one of the examples to prove the connection works?

**Comment by ronhud** [comment]
Just dicovered an earlier question wit5h instruction to run the wait_for_press script, ok now. Thanks

**Comment by martinohanlon** [comment]
Thanks for the speedy response @ukBaz
