### ISSUE TITLE
Raspberry Pi 4 model B shows No matching distribution found for bluedot

### ISSUE THREAD

**Issue by piuser777** [martinohanlon/BlueDot#151]
The following error message shown when I tried to install bluedot on RPi4 model B.

Temporary failure in name resolution')': /simple/bluedot/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb52c1890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/bluedot/

  Could not find a version that satisfies the requirement bluedot (from versions: )
No matching distribution found for bluedot

is the any alternate way?

**Comment by martinohanlon** [comment]
It looks like you can't connect to pypi / piwheels to download the package. It might be a temporary issue so definitely try again.

You can build bluedot from source too. There are instructions on the docs https://bluedot.readthedocs.io/en/latest/build.html
