### ISSUE TITLE
multidot : testing feedback

### ISSUE THREAD

**Issue by bsimmo** [martinohanlon/BlueDot#153]
first time using bluedot.
Huawei Mate20 Pro - Android 10 / EMUI 10.1.0 
Pi3 B+  PiOS/Buster/5.4.51-v7+

Followed instructions and everything working so far (up to gpiozero)
will test further when I find some led and motors and things.

**Comment by martinohanlon** [comment]
Thanks a lot Ben.

**Comment by martinohanlon** [comment]
Thanks for your help @bsimmo. I am hoping to release v2.0.0 today (google play store review pending)
