### ISSUE TITLE
Android app not able to connect to Pi

### ISSUE THREAD

**Issue by biswajek** [martinohanlon/BlueDot#169]
Hi Martin,
I downloaded the latest version from Play Store. My Pi and phone are connected over Bluetooth. However when I open the app
(it shows a list of devices with BL enabled) and tap on Pi  to connect, I get not connected messsage.
Thanks

**Comment by martinohanlon** [comment]
Do you have BlueDot running in Python on the Raspberry Pi.

You will find instructions at https://bluedot.readthedocs.io/en/latest/gettingstarted.html

**Comment by martinohanlon** [comment]
No response so closing.
