### ISSUE TITLE
README.md link to APK gives 404 error

### ISSUE THREAD

**Issue by ukBaz** [martinohanlon/BlueDot#2]
This link seems to be broken:
https://github.com/martinohanlon/BlueDot/blob/android-dev/clients/android/app/app-release.apk?raw=true

I had to use the following link to get a successful install:
https://github.com/martinohanlon/BlueDot/blob/master/clients/android/app/app-release.apk?raw=true

**Comment by martinohanlon** [comment]
Thanks Barry, fixed in development branch.
