### ISSUE TITLE
Setup travis testing

### ISSUE THREAD

**Issue by martinohanlon** [martinohanlon/BlueDot#24]

**Comment by martinohanlon** [comment]
Need to do:

- remove Python - "3.2"
- sort out "ImportError: No module named dbus" error
- remove ^M from .travis.yml

**Comment by martinohanlon** [comment]
Try adding 

sudo: required to .travis.yml

**Comment by martinohanlon** [comment]
Sorted by putting dirty hack into utils.py to check for the travis environment variable and not import dbus if running by travis.

**Comment by ukBaz** [comment]
system_site_packages only works with Python 2.7 and 3.2 on Travis.
If you select just those two versions then you can do apt-get python-dbus

I've also looked at using [python-dbusmock](https://github.com/martinpitt/python-dbusmock) for easing testing of DBUS on Travis

**Comment by martinohanlon** [comment]
@ukBaz yes I found that out by trial and error and then looking at your travis setup!

I wasnt keen to only test with Python 3.2 as I read that bluetooth sockets where only supported from 3.3

**Comment by martinohanlon** [comment]
Setting up travis was just a massive pain due to dbus. so just setup local testing using pytest.

**Comment by ukBaz** [comment]
Hi @martinohanlon ,

It might be too little too late but FYI:
I've also had to abandon testing with dbus on Travis as it was too much pain.
My approach now is to unittest.mock.patch the DBus calls. e.g:
https://github.com/ukBaz/python-bluezero/blob/master/tests/test_adapter_example.py#L16
