### ISSUE TITLE
Display a version number in the app

### ISSUE THREAD

**Issue by ukBaz** [martinohanlon/BlueDot#34]
I'm not sure if my app has been updated with the version from the Play Store. It would be useful if the app displayed a version number somewhere

**Comment by martinohanlon** [comment]
I would prefer not to, versions are managed by Play Store and you can see the version in Settings, Apps, Blue Dot

**Comment by martinohanlon** [comment]
While its a good idea, i fear it would become an administrative challenge which is fulfilled in other ways.
