### ISSUE TITLE
Squares

### ISSUE THREAD

**Issue by erikvanelten** [martinohanlon/BlueDot#43]
I'd very much like an interface that works with squares. A blue dot is cute, but not very functional on a phone or tablet.
Imagine you could define a table with cells that would call a function on touch.

**Comment by martinohanlon** [comment]
I'm sure for a table a square would work better, i feel that is a different project though.

My vision for blue dot was to allow a very very simple interface to start an activity, a button or circle seemed to be the simplest shape allow for more directional based projects and future enhancements like rotations and gestures.

You can use the x,y position to segment the blue dot into any matrix you want though.
