### ISSUE TITLE
Controlable behaviour for out of circle touch.

### ISSUE THREAD

**Issue by dglaude** [martinohanlon/BlueDot#55]
The BlueDot is a blue circle (with a radius of lenght 1) inside a bounding white square (with a side of lenght 2 from -1 to 1).
The behavioud when touching outside the circle but inside the square should be better defined and controlable from the API.
In that area, the distance to the center will be higher than 1 (easy to filter at client side too).
For some usage you want only the circle to be sensitive and to report information, for other usage, you want to benefit from the full square.

**Comment by martinohanlon** [comment]
I think adding additional functions to manage whether the users wants it to be a circle or a square is adding complexity for little benefit.  The key aim of Blue Dot is to be super simple.

If I was going to change anything it would be the app to not trigger outside the circle, although again I dont see a great deal of benefit to doing this.
