### ISSUE TITLE
What is the formula for pos.distance? How can it always be below or equal to 1?

### ISSUE THREAD

**Issue by dglaude** [martinohanlon/BlueDot#60]
I was worry about the value of pos.distance when the finger is outside of the circle.
Mostly because I use it for saturation in my colour picker.

So I added some print debug:
`print(pos.x,pos.y,pos.distance)`

And I get "1 1 1" as one of the possible value.
Obviously distance is not equal to sqrt(x^2+y^2)

I believe the documentation should be updated on this topic.
Anything above 1.0 seems to be rounded to 1.0.

**Comment by martinohanlon** [comment]
The formula is really simple, its the hypot of x,y - it is however, as you have said clamped to 1 - this being the radius of the dot.  

`https://github.com/martinohanlon/BlueDot/blob/master/bluedot/dot.py#L64`

It was originally not clamped, but a number of people raised issues that it was confusing to have a distance > 1 returned.
