### ISSUE TITLE
ios client

### ISSUE THREAD

**Issue by iZhangHui** [martinohanlon/BlueDot#68]
Bluedot is very useful to me. Thank you for your work.
Would you have a plan to develop a Bluedot client for iphone?

**Comment by martinohanlon** [comment]
Unfortunately iOS doesn't support Bluetooth RFCOMM serial data comms which the Blue Dot app uses to talk to Python.

Apple restrict communication to official (made for apple) devices.

You can create you own hand held client by using a raspberry pi and a touch screen tho.
